# Generated by Django 5.2.6 on 2025-09-13 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="otp",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="otp",
            name="phone",
        ),
        migrations.AddField(
            model_name="otp",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="otp",
            name="patient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.patient",
            ),
        ),
        migrations.AlterField(
            model_name="otp",
            name="code",
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
